config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles  do #This told Rails that we were going to follow the RESTful conventions for this model named Article. 
    resources :comments
  end
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings, dependent: :destroy
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

    def tag_list
        tags.join(', ')
    end

    def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
        self.tags = new_or_found_tags
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :articles, through: :taggings

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# @articles? That marks this variable as an "instance level variable". 
# We want the list of articles to be accessible from both the controller and the view 
# that we’re about to create. In order for it to be visible in both places it has to be an instance variable. If we had just named it articles, 
# that local variable would only be available within the index method of the controller.

# Rails has assumed that our "index action" in the controller should
# have a corresponding "index.erb" view template in the views folder. 
class ArticlesController < ApplicationController
    include ArticlesHelper
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
        @comment = Comment.new
        @comment.article_id = @article.id
    end

    def new
        @article = Article.new #Enables us create new article via a form, without it the form won't open when you click "Create New"

    end
        
#    We accessed the "new action" to load the form, but Rails’ interpretation of REST uses a 
#    second action named "create" to process the data from that form. 

    def create
       # Without "create action", you can submit the form
    #    @article = Article.new( The @article so created is an array of objects(hash)
    #     title: params[:article][:title], - @article array contains both 'title & body',article.title
    #     body: params[:article][:body]) - article.body
        @article = Article.new(article_params)
        @article.save
         flash.notice = "Article '#{@article.title}' Created!"
        redirect_to article_path(@article)
    end

    def edit
       @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        @article.update(article_params)
        flash.notice = "Article '#{@article.title}' Updated!"
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash.notice = "Article '#{@article.title}' has been deleted Successfully!"
         
        redirect_to articles_path
        
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    include CommentsHelper
    def create
        @comment = Comment.new(comment_params)
        @comment.article_id = params[:article_id]

        @comment.save

        redirect_to article_path(@comment.article)
   end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = Tag.all
    end
    
    def show
      @tag = Tag.find(params[:id])
    end
    def destroy
        @tags = Tag.find(params[:id])
        @tags.destroy
        flash.notice = "'#{@tags.name}' has been deleted Successfully!"
         
        redirect_to tags_path
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def article_params
        params.require(:article).permit(:title, :body, :tag_list, :image)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def comment_params
    params.require(:comment).permit(:author_name, :body)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Author: <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <%# <p>
    <%= f.label :image, "Attach an Image" %><br />
  <%# <%= f.file_field :image %>
  <%# </p> %>
  <p>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>
<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>
<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>
<%# Why the name "new.html.erb?"" The first piece, new, matches the name of the controller method. 
The second, html, specifies the output format sent to the client. The third, erb, specifies the language the template is written in. 
Under different circumstances, we might use new.json.erb to output JSON or 
new.html.haml to use the HAML templating language. %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<p><% if @article.image.exists? %>
    <%= image_tag @article.image.url(:medium) %><br/>
  <% end %></p>
<p><%= @article.body %></p>
<%= render partial: 'comments/form' %>
<%= link_to "<< Back to Articles List", articles_path %>
<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %>
<%= link_to "edit", edit_article_path(@article) %>
<h3>Comments (<%= @article.comments.size %>)</h3>
<%# This means for each of the collectn of '@article.comments', give us the 'author_name'& 'comment.bobdy' as represented in the partial %>
<%# The partial is _comment.html.erb and located inside the 'articles' folder - hence "render partial: 'articles/comment'" %>
<%= render partial: 'articles/comment', collection: @article.comments %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRailsTemplate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>
<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
      <%=tag.name%>
    </li>
  <% end %>
</ul>
<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>
<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
  <%= link_to "<< Back to Tags List", articles_path %>
  <%= link_to "delete Tag", tag_path(@tag), method: :delete, data: {confirm: "Really delete the article?"} %>
</ul>